### ISSUE TITLE
Luarocks issue unrelated to JWT

### ISSUE THREAD

**Issue by lordnynex** [Olivine-Labs/lua-jwt#4]
@DorianGray I can not file an issue at your [lua-cjson](https://github.com/DorianGray/lua-cjson) repo because it is a fork. 

I appreciate the addition to that module because the empty table encoding of cjson can be frustrating. Unfortunately, you've published this module to luarocks declaring 'cjson' as the modules one and only name(space). This is a big problem for my other projects. For example, I've recently submitted a patch to openresty to increase maximum float precision for cjson. I use this for generating sequence ID's between server and client. Unfortunately, that project is now broken because I used luarocks to install lua-jwt which pulls in lua-cjson-ol as a dependency. 

I'm not sure what the best way to fix this in luarocks is. Maybe @leafo can help. Would it be possible to publish an updated version of this module that uses a different namespace entirely?

**Comment by leafo** [comment]
Not sure there's a good way to handle this, I think the best fix would be to name the module differently.

**Comment by DorianGray** [comment]
Hmm, alright, I didn't think too far ahead with the fork. I'll rename the lua part.

**Comment by lordnynex** [comment]
@DorianGray Thanks for your help. Sorry for any inconvenience.
